### ISSUE TITLE
how to make the meltdown toy to compile 

### ISSUE THREAD

**Issue by Hsinhsing** [msmania/microarchitectural-attack#1]
I am trying the meltdown toy, any more instructions about how to compile it? Thank you very much.

**Comment by Hsinhsing** [comment]
thank you, I think I successfully made it to work...

**Comment by msmania** [comment]
Great! Glad to head that.

**Comment by Hsinhsing** [comment]
hello, I tried to compile the spectre toy( the meltdown toy I also can not compile any more, but lucky I have an exe file from the last time), but I cannot make it happen, do you have the exe files that I can make a test? Thank you very much. '

Regards,
Hsinhsing

**Comment by msmania** [comment]
Sure, I added [Releases](https://github.com/msmania/microarchitectural-attack/releases).  Enjoy!

**Comment by Hsinhsing** [comment]
Thank you very much !
